### ISSUE TITLE
node 10 build faild

### ISSUE THREAD

**Issue by moshengrenzenme** [catalogm/node-xapian#6]
npm ERR! path test_project/xapian/node_modules/_xapian@0.0.1@xapian/node_modules/xapian
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: 进入目录“test_project/xapian/node_modules/_xapian@0.0.1@xapian/node_modules/xapian/build”
npm ERR!   CXX(target) Release/obj.target/xapian/src/module.o
npm ERR! make: 离开目录“test_project/xapian/node_modules/_xapian@0.0.1@xapian/node_modules/xapian/build”
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@10.15.3 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [ '/node/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'test_project/xapian/node_modules/_xapian@0.0.1@xapian/node_modules/xapian/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/node/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/a/.cache/node-gyp/10.15.3/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/a/.cache/node-gyp/10.15.3',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/node/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/a/.cache/node-gyp/10.15.3/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=test_project/xapian/node_modules/_xapian@0.0.1@xapian/node_modules/xapian',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.' ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from test_project/xapian/node_modules/_node-addon-api@2.0.2@node-addon-api/napi.h:2171,
npm ERR!                  from ../src/module.cc:2:
npm ERR! test_project/xapian/node_modules/_node-addon-api@2.0.2@node-addon-api/napi-inl.h: In member function ‘bool Napi::Value::IsDate() const’:
npm ERR! test_project/xapian/node_modules/_node-addon-api@2.0.2@node-addon-api/napi-inl.h:416:24: error: ‘napi_is_date’ was not declared in this scope; did you mean ‘napi_is_dataview’?
npm ERR!   416 |   napi_status status = napi_is_date(_env, _value, &result);
npm ERR!       |                        ^~~~~~~~~~~~
npm ERR!       |                        napi_is_dataview
npm ERR! test_project/xapian/node_modules/_node-addon-api@2.0.2@node-addon-api/napi-inl.h: In static member function ‘static Napi::Date Napi::Date::New(napi_env, double)’:
npm ERR! test_project/xapian/node_modules/_node-addon-api@2.0.2@node-addon-api/napi-inl.h:711:24: error: ‘napi_create_date’ was not declared in this scope; did you mean ‘napi_create_dataview’?
npm ERR!   711 |   napi_status status = napi_create_date(env, val, &value);
npm ERR!       |                        ^~~~~~~~~~~~~~~~
npm ERR!       |                        napi_create_dataview
npm ERR! test_project/xapian/node_modules/_node-addon-api@2.0.2@node-addon-api/napi-inl.h: In member function ‘double Napi::Date::ValueOf() const’:
npm ERR! test_project/xapian/node_modules/_node-addon-api@2.0.2@node-addon-api/napi-inl.h:728:24: error: ‘napi_get_date_value’ was not declared in this scope; did you mean ‘napi_get_reference_value’?
npm ERR!   728 |   napi_status status = napi_get_date_value(
npm ERR!       |                        ^~~~~~~~~~~~~~~~~~~
npm ERR!       |                        napi_get_reference_value
npm ERR! make: *** [xapian.target.mk:113：Release/obj.target/xapian/src/module.o] 错误 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! gyp ERR! System Linux 5.4.0-74-generic
npm ERR! gyp ERR! command "/node/bin/node" "/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd test_project/xapian/node_modules/_xapian@0.0.1@xapian/node_modules/xapian
npm ERR! gyp ERR! node -v v10.15.3
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

**Comment by kelvinhammond** [comment]
Hello @moshengrenzenme, it looks like the function `napi_create_date` and others are available in the node v10.15.3 version. You may need to update to a newer version. Node 10 is also now unmaintained from what I can see here https://nodejs.org/en/about/releases/ .
